config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do 
  	collection do
      get :my_calender
      get :my_events
      post :join_event
    end

  end 
  root 'visitors#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
   belongs_to :user
   belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many :attendees, dependent: :destroy
  
  validates :title, presence: true
  attr_accessor :date_range

  def all_day_event?
    self.start == self.start.midnight && self.end == self.end.midnight ? true : false
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :events, dependent: :destroy
  has_many :attendees, dependent: :destroy
  devise :database_authenticatable, :registerable,
       :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name,:current_password) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name,:current_password) }
	  #devise_parameter_sanitizer.for(:sign_up) << :name
	  #devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events ||= Event.where(start: params[:start]..params[:end])
  end

  def my_events
    @events = current_user.events
    render "index"
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.save
  end

  def update
    @event.update(event_params)
  end

  def destroy
    @event.destroy
  end

  def my_calender
    
  end

  def join_event
    @event = Event.find_by_id(params[:event_id])
    @attendee = Attendee.create(attendee_params)
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:title, :date_range, :start, :end, :color,:user_id)
    end

    def attendee_params
      params.permit(:event_id,:user_id)
    end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/events/_edit.html.erb
<div class="modal fade" id="edit_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <% if params[:action] == "edit" && @event.user.id ==  current_user.id %>
          <h4 class="modal-title">Edit Event</h4>
         <% else %>  
          <h4 class="modal-title">View Event</h4>
         <% end %>
      </div>
      <div class="modal-body">
        <%= render 'form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<% if user_signed_in? %>
  <%= simple_form_for @event, remote: true do |f| %>
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :date_range, input_html: { class: "form-control input-sm date-range-picker" } %>
      <%= f.input_field :start, as: :hidden, value: Date.today, class: 'form-control input-sm start_hidden' %>
      <%= f.input_field :end, as: :hidden, value: Date.today, class: 'form-control input-sm end_hidden' %>
      <%= f.input_field :user_id, as: :hidden, value: @event.user_id.present? ? @event.user_id : current_user.id %>
      <%= f.input :color, as: :select, collection: [['Black','black'], ['Green','green'], ['Red','red']] %>
    </div>
  <% if params[:action] == "edit" && @event.user.id ==  current_user.id %>
      <div class="form-actions">
        <%= f.button :submit %>
        <%= link_to 'Delete', 
                    event, 
                    method: :delete, 
                    class: 'btn btn-danger', 
                    data: { confirm: 'Are you sure?' }, 
                    remote: true unless @event.new_record? %>



      </div>
   <% end %>
        <% unless @event.attendees.where(user_id: current_user.id).present? %> 
         <% if @event.user_id != current_user.id %>        
           <%= link_to "Join Event", join_event_events_path(event_id: @event.id, user_id: current_user.id), :confirm => 'Are you want to join?', :class => "btn join_event btn-info", :method => :post,remote: true %>
          <% end %>
         <% else %>
         <%= link_to "Joined","#",:class => "btn btn-success" %>
        <% end %>
        <div>Those who are going </div>
          <ul class="list-group">
        <% @event.attendees.each do |attendee| %>
          <li class="list-group-item"><%= attendee.user.name %></li>
        <% end %>
         </ul>
<% end %>
<% else %> 
<p>
Please login before create or edit any event
<p>
<% end %>

app/views/events/_new.html.erb
<div class="modal fade" id="new_event">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title">Create New Event</h4>
      </div>
      <div class="modal-body">
        <%= render 'new_form', event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/_new_form.html.erb
<% if user_signed_in? %>
  <%= simple_form_for @event, remote: true do |f| %>
    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :date_range, input_html: { class: "form-control input-sm date-range-picker" } %>
      <%= f.input_field :start, as: :hidden, value: Date.today, class: 'form-control input-sm start_hidden' %>
      <%= f.input_field :end, as: :hidden, value: Date.today, class: 'form-control input-sm end_hidden' %>
      <%= f.input_field :user_id, as: :hidden, value: @event.user_id.present? ? @event.user_id : current_user.id %>
      <%= f.input :color, as: :select, collection: [['Black','black'], ['Green','green'], ['Red','red']] %>
    </div>
      <div class="form-actions">
        <%= f.button :submit %>
        <%= link_to 'Delete', 
                    event, 
                    method: :delete, 
                    class: 'btn btn-danger', 
                    data: { confirm: 'Are you sure?' }, 
                    remote: true unless @event.new_record? %>
      </div>
<% end %>
<% else %> 
<p>
Please login before create or edit any event
<p>

<% end %>

app/views/events/create.js.erb
$('.calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.my_calender').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"),
  true
);
$('.modal').modal('hide');

app/views/events/destroy.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>])
$('.my_calender').fullCalendar('removeEvents', [<%= @event.id %>])
$('.modal').modal('hide');

app/views/events/edit.js.erb
$('#remote_container').html('<%= j render "edit" %>');
$('#edit_event').modal('show');

app/views/events/join_event.js.erb
$('.join_event').attr("href","#");
$('.join_event').text("Joined");
$('.join_event').addClass("btn-success");
<% attendee_name = @attendee.user.name %>
$('.list-group').append("<li class='list-group-item'><%= attendee_name %></li>")
//$('#edit_event').modal('show');

app/views/events/my_calender.html.erb
<div class="my_calender"></div>

app/views/events/new.js.erb
$('#remote_container').html('<%= j render "new" %>');
$('#new_event').modal('show');

app/views/events/update.js.erb
$('.calendar').fullCalendar('removeEvents', [<%= @event.id %>]);
$('.calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@event, format: :json).html_safe %>"), 
  true
);
$('.modal').modal('hide');

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    <ul class="nav navbar-nav pull-right">

      <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'My Event Calender', my_calender_events_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
         <%= link_to 'Log In', new_user_session_path, class: 'navbar-brand' %>
          <%= link_to 'Sign Up', new_user_registration_path, class: 'navbar-brand' %>
        <% end %>
      </ul>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Template" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Template" %>">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class='container'>
        <%= render 'layouts/messages' %>
        <%= yield %>
        <div id='remote_container'></div>
      </div>
    </main>
  </body>
</html>

app/views/visitors/index.html.erb
 <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>See your event here</p>
    </div>
  </div>


<div class="calendar"></div>